<?php

/**
 * @var $this Billmate_Checkout_Block_Checkout
 */

$bmIframeUrl = $this->getBmIframeUrl();
?>
<?php echo $this->getChildHtml('checkout.cart'); ?>
<script>
    var UPDATE_ADDRESS_URL = "<?php echo Mage::getUrl('billmatecheckout/index/updateaddress',array('_secure' => true)); ?>";
    var UPDATE_PAYMENT_METHOD_URL = "<?php echo Mage::getUrl('billmatecheckout/index/updatepaymentmethod',array('_secure' => true)); ?>";
    var UPDATE_SHIPPING_METHOD_URL = "<?php echo Mage::getUrl('billmatecheckout/index/updateshippingmethod',array('_secure' => true)); ?>";
    var CREATE_ORDER_URL = "<?php echo Mage::getUrl('billmatecheckout/index/createorder',array('_secure' => true)); ?>";
    var UPDATE_TOTALS_URL = "<?php echo Mage::getUrl('billmatecheckout/index/updatetotals',array('_secure' => true)); ?>";
    var UPDATE_DISCOUNT_URL = "<?php echo Mage::getUrl('billmatecheckout/index/setdiscount',array('_secure' => true)); ?>";
    var CHECKOUT_URL = "<?php echo Mage::getUrl('billmatecheckout/index/index',array('_secure' => true)); ?>"
</script>
<div id="checkout-loader">
    <div class="img-loader"></div>
</div>
<div class="messages">
    <?php echo $this->getMessagesBlock() ?>
</div>
<div id="checkoutdiv">
    <iframe id="checkout" src="<?php echo $bmIframeUrl; ?>" style="width: 100%; min-height: 800px; border:none;" sandbox="allow-same-origin allow-scripts allow-modals allow-popups allow-forms allow-top-navigation"></iframe>
    <div class="billmateoverlay"></div>
    <div class="billmateloading"></div>
</div>

